name: Deploy to NPM

on:
  push:
    branches:
      - main

jobs:
  deploy_base:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
      TURBO_REMOTE_ONLY: true

    steps:
    - name: Setup - Checkout
      uses: actions/checkout@v1

    - name: Setup - Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Publish Base
      run: cd packages/base && npm publish

  deploy_remix:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
      TURBO_REMOTE_ONLY: true

    steps:
    - name: Setup - Checkout
      uses: actions/checkout@v1

    - name: Setup - Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Publish Remix
      run: cd packages/remix && npm publish
