name: Deploy to NPM

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  publish:
    name: Publish Packages to NPM
    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
      TURBO_REMOTE_ONLY: true

    steps:
    - name: Setup - Checkout
      uses: actions/checkout@v1

    - name: Setup - Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy Base Package
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/base/package.json
        access: public

    - name: Deploy Remix Package
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/remix/package.json
        access: public
